CREATE TABLE public.entrega
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    data_pedido timestamp without time zone NOT NULL,
    data_finalizacao timestamp without time zone,
    destinatario_bairro character varying(50) COLLATE pg_catalog."default" NOT NULL,
    destinatario_complemento character varying(50) COLLATE pg_catalog."default",
    destinatario_logradouro character varying(50) COLLATE pg_catalog."default" NOT NULL,
    destinatario_nome character varying(100) COLLATE pg_catalog."default" NOT NULL,
    destinatario_numero character varying(20) COLLATE pg_catalog."default" NOT NULL,
    status character varying(30) COLLATE pg_catalog."default" NOT NULL,
    taxa numeric(19,2) NOT NULL,
    cliente_id bigint NOT NULL,
    CONSTRAINT entrega_pkey PRIMARY KEY (id),
    CONSTRAINT fk6s5qo326hpov2shx1c5wmnofk FOREIGN KEY (cliente_id)
        REFERENCES public.cliente (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.entrega
    OWNER to postgres;